config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :comments, module: :board, only: [:create, :destroy]
  end
  resources :posts do
    resources :comments, module: :post, only: [:create, :destroy]
  end
  root 'posts#index'
  get 'home/index'
  post '/tinymce_assets' => 'tinymce_assets#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :boardimage, ImageUploader

  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  validates :comment, presence: true
  validates :title, presence: true
  def post
    self.commentable
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :comments, as: :commentable

  paginates_per 3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board/comments_controller.rb
class Board::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Board.find(params[:board_id])
    @url= :board
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show

  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :content, :boardimage)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.js
      end
    else

    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:comment, :title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/post/comments_controller.rb
class Post::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Post.find(params[:post_id])
    @url= :post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
  def create
    file = params[:file]
    uploader = ImageUploader.new

    uploader.store!(file)
    render json: {
      image: {
        url: uploader.url
      }
    }, content_type: "text/html"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/_form.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="container-fluid">
    <div class="col-md-6">
      <%= form_with(model: board, local: true) do |form| %>
        <% if board.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

            <ul>
            <% board.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :"제목" %>
          <%= form.text_field :title, :class => "form-control", :placeholder => "제목" %>
        </div>

        <div class="field">
          <%= form.label :"내용" %>
          <%= form.text_area :content, :class => "form-control", :rows => "8" %>
        </div>

        <div class="field">
          <%= form.label :"파일" %>
          <%= form.file_field :boardimage, :class => "form-control" %>
        </div>
        <br />
        <div class="actions">
          <center>
            <%= form.submit "작성" %>
          </center>
        </div>
        <br />
      <% end %>
      <center>
        <%= link_to '뒤로 가기', boards_path %>
      </center>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<%= render 'shared/header' %>
<%= render 'form', board: @board %>
<%= render 'shared/footer' %>

app/views/boards/index.html.erb
<%= render 'shared/header' %>
<div align="center">
  <table class="type11">
    <thead>
      <tr align="center">
        <th style="width:50px; text-align:center;">번호</th>
        <th style="width:300px; text-align:center;">제목</th>
        <th style="width:100px; text-align:center;">작성일</th>
      </tr>
    </thead>

    <tbody>
      <% @boards.each do |board| %>
        <tr align="center">
          <td><%= board.id %></td>
          <td><%= link_to board.title, board %></td>
          <% @time_convert = board.created_at.strftime("%Y-%m-%d") %>
          <td><%= @time_convert %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="col-md-12 text-center animate-box">
    <p><%= link_to '할 일 등록', new_board_path, :class => "btn btn-primary btn-lg btn-learn" %></p>
  </div>
</div>
<%= render "shared/footer" %>

app/views/boards/new.html.erb
<%= render 'shared/header' %>
<%= render 'form', board: @board %>
<%= render 'shared/footer' %>

app/views/boards/show.html.erb
<%= render 'shared/header' %>
<div class="overlay"></div>
<div class="container">
  <div class="row animate-box">
    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
      <h2><%= @board.title %></h2>
      <div class="panel-body">
        <%= @board.content %><br /><br />
        <% if @board.boardimage.present? %>
          파일명을 클릭하면 다운로드 됩니다.<br /><br />
          <%= link_to "#{@board.title}", @board.boardimage_url, download: "#{@board.title}" %>
        <% end %>
      </div>
      <div class="panel-body">
        <div id="comments" class="comments">
          <!--댓글 달기폼-->
          <%= render 'comments/form', commentable: @board, url: :board %><br />
          <!--댓글 달기 폼끝-->
          <!--댓글 리스트 반복문 시작 -->
          <div class="comment-list">
            <% count = 0 %>
            <% @board.comments.each do |comment| %>
                <!--count보다 더 많이 돌아가는 버그-->
                <% unless count >= @board.comments.count %>
                    <!--댓글달기 ajax용 렌더-->
                    <%= render 'comments/item', comment: comment, url: :board %>
                <% end %>
                <% count+=1 %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row animate-box">
    <div class="col-md-8 col-md-offset-2 text-center">
      <p><%= link_to 'Edit', edit_board_path(@board), :class => "btn btn-default btn-lg" %>
      <%= link_to 'Back', boards_path, :class => "btn btn-default btn-lg" %></p>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/comments/_comment.html.erb
<div class="comment-list">
  <% case url %>
  <% when :blog then
       id= :blog_id %>
  <% end %>
  <% count =0 %>
  <% commentable.comments.each do |c| %>
      <!--count보다 더 많이 돌아가는 버그-->
      <% unless count >= commentable.comments.count %>
          <% case url %>
  <% when :blog then
       id= :blog_id %>

          <% when :boards then
               id= :boards %>
          <% end %>
      <% end %>
  <% end %>
</div>

app/views/comments/_form.erb
<% case url %>
<% when :board then @path=url_for(controller: "board/comments", action: :create, board_id: commentable.id) %>
<% when :post then @path=url_for(controller: "post/comments", action: :create, post_id: commentable.id) %>
<% end %>

<div class="panel-body">
  <%= form_for [commentable, commentable.comments.new], url: @path, remote: true do |f| %>
    <div class="input-field">
      <%= f.text_field :title, class: "form-control", placeholder: "작성자", required: true, id: "comment_title" %>
      <%= f.text_area :comment, class: "form-control", placeholder: "댓글 쓰기", required: true, id: "comment_body", rows: "3" %>
    </div>
    <br />
    <div class="input-field">
      <%= f.button "댓글 쓰기", class: "btn indigo darken-4 right" %>
    </div>
  <% end %>
</div>

app/views/comments/_item.erb
<div class="row" id="comment-<%= comment.id %>">
  <div class="col-md-2 col-sm-2 hidden-xs">
    <figure class="thumbnail">
      <figcaption class="text-center"><%= comment.title %></figcaption>
    </figure>
  </div>
  <div class="col-md-10 col-sm-10">
    <div class="panel panel-default arrow left">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-10 col-sm-10">
            <header class="text-left">
              <div class="comment-user"><i class="fa fa-user"></i> <%= comment.comment %></div>
            </header>
          </div>
          <div class="col-md-2 col-sm-2">
          </div>
        </div>

        <div class="comment-post">

        </div>
        <!--<p class="text-right">-->
        <!--<a href="#" class="btn btn-default btn-sm"><i class="fa fa-check"></i>채택하기</a>-->
        <!--</p>-->
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
(function ($) {
    console.log("<%= @comment.comment %>")
    $("#comment_title").val("")
    $("#comment_body").val("")
    <%if @url==:post2 %>
    var html = "<%= escape_javascript(render(partial: 'comments/item', locals: {comment: @comment, url: @url,  category: @category})) %>";
    <%elsif @url==:submission%>
    var html = "<%= escape_javascript(render(partial: 'comments/item', locals: {comment: @comment, url: @url,  task: @task})) %>";
    <% else %>
    var html = "<%= escape_javascript(render(partial: 'comments/item', locals: {comment: @comment, url: @url})) %>";
    <%end%>
    $("#comments").append(html);
})(jQuery)

app/views/comments/destory.js.erb
(function($){
    console.log("삭제된다")
    $("#comment-<%= @comment.id %>").remove();
})(jQuery)

app/views/home/index.html.erb
<%= render 'shared/header' %>

<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>com1san3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'false' %>

    <!--<link rel="shortcut icon" href="/favicon.ico">-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--
    //////////////////////////////////////////////////////

    FREE HTML5 TEMPLATE
    DESIGNED & DEVELOPED by FreeHTML5.co

    Website: 		http://freehtml5.co/
    Email: 			info@freehtml5.co
    Twitter: 		http://twitter.com/fh5co
    Facebook: 		https://www.facebook.com/fh5co

    //////////////////////////////////////////////////////
     -->

      <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="/css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="/css/magnific-popup.css">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <!-- Flexslider  -->
    <link rel="stylesheet" href="/css/flexslider.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="/css/style.css">

  </head>

  <body>
    <%= tinymce_assets %>
    <%= yield %>
    <!-- Modernizr JS -->
    <script src="/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="/js/jquery.waypoints.min.js"></script>
    <!-- Stellar Parallax -->
    <script src="/js/jquery.stellar.min.js"></script>
    <!-- Carousel -->
    <script src="/js/owl.carousel.min.js"></script>
    <!-- Flexslider -->
    <script src="/js/jquery.flexslider-min.js"></script>
    <!-- countTo -->
    <script src="/js/jquery.countTo.js"></script>
    <!-- Magnific Popup -->
    <script src="/js/jquery.magnific-popup.min.js"></script>
    <script src="/js/magnific-popup-options.js"></script>
    <!-- Main -->
    <script src="/js/main.js"></script>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="container-fluid">
    <div class="col-md-6">
      <%= form_with(model: post, local: true) do |form| %>
        <% if post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :"제목" %>
          <%= form.text_field :title, :class => "form-control", :placeholder => "제목" %>
        </div>

        <div class="field">
          <%= form.label :"내용" %>
          <%= form.text_area :content, :class => "form-control", :rows => "8" %>
        </div>

        <div class="field">
          <%= form.label :"파일" %>
          <%= form.file_field :image, :class => "form-control" %>
        </div>

        <div class="actions">
          <center>
            <%= form.submit "작성" %>
          </center>
        </div>
      <% end %>
      <center>
        <%= link_to '뒤로 가기', posts_path %>
      </center>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/header' %>
<%= render 'form', post: @post %>
<%= render 'shared/footer' %>

app/views/posts/index.html.erb
<%= render 'shared/header' %>
<div id="fh5co-practice" class="fh5co-bg-section">
  <div class="container">
    <div class="row animate-box">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <h2>깔깔</h2>
        <p>깔깔깔깔깔</p>
      </div>
    </div>
    <div class="row">
      <% @posts.each do |post| %>
      <div class="col-md-4 text-center animate-box">
        <div class="services">
          <span class="icon">
            <i class="icon-food"></i>
          </span>
          <div class="desc">
            <h3><%= post.title %></h3>
            <p>
              <%= link_to '보기', post %> | <%= link_to '수정', edit_post_path(post) %><br /><br />
              <% @time_convert = post.created_at.strftime("%Y-%m-%d") %>
              <%= @time_convert %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
      <div class="col-md-12 text-center animate-box">
        <p><%= link_to 'New Post', new_post_path, :class => "btn btn-primary btn-lg btn-learn" %></p>
      </div>
      <div class="col-md-12 text-center animate-box">
        <p>
          <%= will_paginate @posts, :previous_label => '이전', :next_label => '다음' %>
        </p>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/posts/new.html.erb
<%= render 'shared/header' %>
<%= render 'form', post: @post %>

<%= render 'shared/footer' %>

app/views/posts/show.html.erb
<%= render 'shared/header' %>
<div class="overlay"></div>
<div class="container">
  <div class="row animate-box">
    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
      <h2><%= @post.title %></h2>
      <div class="panel-body">
        <%= @post.content %><br /><br />
          파일명을 클릭하면 다운로드 됩니다.<br /><br />
          <%= link_to "#{@post.title}", @post.image_url, download: "#{@post["image"]}" %>
      </div>
      <div class="panel-body">
        <div id="comments" class="comments">
          <!--댓글 달기폼-->
          <%= render 'comments/form', commentable: @post, url: :post %><br />
          <!--댓글 달기 폼끝-->
          <!--댓글 리스트 반복문 시작 -->
          <div class="comment-list">
            <% count = 0 %>
            <% @post.comments.each do |comment| %>
                <!--count보다 더 많이 돌아가는 버그-->
                <% unless count >= @post.comments.count %>
                    <!--댓글달기 ajax용 렌더-->
                    <%= render 'comments/item', comment: comment, url: :post %>
                <% end %>
                <% count+=1 %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row animate-box">
    <div class="col-md-8 col-md-offset-2 text-center">
      <p><%= link_to 'Edit', edit_post_path(@post), :class => "btn btn-default btn-lg" %>
      <%= link_to 'Back', posts_path, :class => "btn btn-default btn-lg" %></p>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">데이터 분석</small>
          <small class="block">#다빈치</small>
        </p>
        <p>
          <ul class="fh5co-social-icons">
            <li><a href="#"><i class="icon-twitter"></i></a></li>
            <li><a href="#"><i class="icon-facebook"></i></a></li>
            <li><a href="#"><i class="icon-linkedin"></i></a></li>
            <li><a href="#"><i class="icon-dribbble"></i></a></li>
          </ul>
        </p>
      </div>
    </div>

  </div>
</footer>

app/views/shared/_header.html.erb
<div class="fh5co-loader"></div>

<div id="page">
  <nav class="fh5co-nav" role="navigation">
    <div class="top-menu">
      <div class="container">
        <div class="row">
          <div class="col-xs-6">
            <div id="fh5co-logo"><a href="/">COM1SAN3<span>.</span></a></div>
          </div>
          <div class="col-xs-6 text-right menu-1">
            <ul>
              <li><a href="/posts">데이터</a></li>
              <li><a href="/boards">TO DO</a></li>
              <!-- <li><a href="practice.html">Practice Areas</a></li>
              <li><a href="won.html">Won Cases</a></li>
              <li class="has-dropdown">
                <a href="blog.html">Blog</a>
                <ul class="dropdown">
                  <li><a href="#">Web Design</a></li>
                  <li><a href="#">eCommerce</a></li>
                  <li><a href="#">Branding</a></li>
                  <li><a href="#">API</a></li>
                </ul>
              </li>
              <li><a href="about.html">About</a></li>
              <li><a href="contact.html">Contact</a></li>
              <li class="btn-cta"><a href="#"><span>Login</span></a></li>
              <li class="btn-cta"><a href="#"><span>Sign Up</span></a></li> -->
            </ul>
          </div>
        </div>

      </div>
    </div>
  </nav>
</div>